name: Compile CV

on:
  push: {}
  pull_request: {}

permissions:
  contents: write
  pull-requests: write 

jobs:
  compile:
    name: Compile CV
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - uses: actions/checkout@master
      name: Checkout repository
      with:
        fetch-depth: 0

    - name: Change ownership
      run: chown -R $(whoami) .

    - name: Compile
      run: xelatex SergeyKambalin.tex

    - name: Commit changes
      run: |
        git config --local user.email "kambalin@gmail.com"
        git config --local user.name "Sergey Kambalin"
        git commit -a -m "[skip ci] Auto-update CV"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - uses: actions/upload-artifact@v4
      name: Upload CV
      with:
        name: SergeyKambalin
        path: ./SergeyKambalin.pdf