name: Compile CV

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile
      run: xelatex SergeyKambalin.tex

    - uses: actions/upload-artifact@v4
      with:
        name: SergeyKambalin
        path: ./SergeyKambalin.pdf